### ISSUE TITLE
group element not in xliff

### ISSUE THREAD

**Issue by peterfarrant** [iLib-js/loctool#127]
The release notes say (which is good as Microsoft Multilingual tool is expecting it)

> Published as version 2.10.0 New Features:
> Added group element under the file element in Xliff format. it is categorized per datatype.

But I am running 2.10.0 and not seeing this in the xliff files (sample test file output below)

> C:\Code\xlifftest>node c:\code\node_modules\loctool\loctool.js -v
> loctool v2.10.0 Copyright (c) 2016-2017, 2019-2020, HealthTap, Inc. and JEDLSoft

```
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2">
  <file original="sources\_index.md" source-language="en-US" target-language="fr-FR" product-name="CDocs">
    <body>
      <trans-unit id="1" resname="r313572260" restype="string" datatype="markdown">
        <source>Add some color</source>
        <target state="new">Add some coloure</target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

**Comment by ehoogerbeets** [comment]
That release note was not clear... the group element only applies to xliff v2.0 format files.

**Comment by peterfarrant** [comment]
That does add it in for v2

Interesting - Microsoft are expecting it in their 1.2 xliff - but they are a bit of a law to themselves
I have also found that the Multilingual toolkit editor removes the resname="r788948019" from the <trans-unit> label 
- is that essential for loctool ?

**Comment by ehoogerbeets** [comment]
Yes, unfortunately, the resname attribute is necessary because it is the unique key for the translation unit. It is a valid attribute on the trans-unit tag: http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#resname

As for the group tag, it is optional. Does MTE require it? What is the reason you are asking about it?

**Comment by peterfarrant** [comment]
We use Microsoft MTE for our code translations as we can then use the Azure Machine translations of xliff for resx files for c#.net, for the Angular code xliff ones we have to makes some changes before it will accept them - which is why we were aware of group tag requirement and some other tweaks that it wants in structure and have a little program to 'prepare' xliffs for MTE that just amends some labels (eg add `translate="yes"` on the trans-unit line).

However Microsoft MTE seems to just use the id fields for its unique identifier and removes the other info on saving.
Example 1 - structure happy for it to edit and save:
```
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2">
  <file original="sources\_index.md" source-language="en-US" target-language="fr-CA" product-name="CDocs">
    <body>
      <group id="sources\_index.md">
        <trans-unit id="1" resname="r804105091" restype="string" datatype="markdown" translate="yes">
          <source>Introduction</source>
          <target state="new">Introduction</target>
        </trans-unit>
        <trans-unit id="4" resname="r788948019" restype="string" datatype="markdown" translate="yes">
          <source>I need to add to this text again</source>
          <target state="new">I need to add to this text again</target>
        </trans-unit>
```
Example 2 after it has saved with one translation change:
```
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2">
  <file datatype="xml" source-language="en-US" target-language="fr-CA" original="sources\_index.md" tool-id="MultilingualAppToolkit" product-name="CDocs" product-version="n/a" build-num="n/a">
    <header>
      <tool tool-id="MultilingualAppToolkit" tool-name="Multilingual App Toolkit" tool-version="4.0.1916.0" tool-company="Microsoft" />
    </header>
    <body>
      <group id="sources\_index.md" datatype="resx">
        <trans-unit id="1" translate="yes" xml:space="preserve">
          <source>Introduction</source>
          <target state="translated">Introduction yes</target>
        </trans-unit>
        <trans-unit id="4" translate="yes" xml:space="preserve">
          <source>I need to add to this text again</source>
          <target state="new">I need to add to this text again</target>
        </trans-unit>
```
Here is a sample from a C# resx xlf
```
      <group id="CLOUD.IDP/RESOURCES/MESSAGES.RESX" datatype="resx">
        <trans-unit id="I've forgotten my password" translate="yes" xml:space="preserve">
          <source>I've forgotten my password</source>
          <target state="new">I've forgotten my password</target>
        </trans-unit>
```
And one from an Angular resx xlf
```
      <group id="ng2.template">
        <trans-unit id="9b2bd34897f127e69e5f02f64692fca98a5a7572" datatype="html">
          <source>Close</source>
          <target state="new">Close</target>
          <context-group purpose="location">
            <context context-type="sourcefile">../node_modules/@progress/kendo-angular-dialog/dist/es2015/dialog/dialog-titlebar.component.d.ts</context>
            <context context-type="linenumber">5</context>
          </context-group>
          <note priority="1" from="description">The title of the close button</note>
          <note priority="1" from="meaning">kendo.dialog.closeTitle</note>
        </trans-unit>
 
```
It would appear both C# and Angular are providing a unique trans-unit id (via different methods; C# unique descriptive key, Angular guid type of key) across all changes, whereas loctool appears to use the resname for uniqueness across all changes and future edits but has trans-unit id from 1 going up consecutively in each run and not unique across multiple changes.

I have found XLF editors Poedit that is quite happy with loctool output as it arrives and does not 'muck it up' on saving - so not asking for a change - just providing information on some different implementations of the '_standard_'

**Comment by peterfarrant** [comment]
One of my developers has found (from internet hunting) that if you change the header to tell it that it is the author program then MTE does not remove the additional entries 

` <header>
      <tool tool-id="MultilingualAppToolkit" tool-name="Multilingual App Toolkit" tool-version="4.0.1916.0" tool-company="Microsoft" />
    </header>`

Happy this is not your issue
